### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Evolvee** [XyzKangUI/SimpleAuraFilter#1]
![image](https://user-images.githubusercontent.com/1942409/188967617-358da913-aebf-43df-ac8f-d9bd0d6cd5f5.png)

**Comment by XyzKangUI** [comment]
Did  you try to hide a buff while in combat?

**Comment by Evolvee** [comment]
Its possible, it also happened AFTER i reloaded during raid and didnt try to hide anything for a long time.

**Comment by XyzKangUI** [comment]
Actually the addon sucks a bit. You are not allowed to cancel buffs in combat due to it being a secure frame.

**Comment by Evolvee** [comment]
There is an addon "Bufflehead" that allegedly fixes the taint thats causing the combat cancel issue.

**Comment by XyzKangUI** [comment]
> There is an addon "Bufflehead" that allegedly fixes the taint thats causing the combat cancel issue.

Yes I saw that we could use a secure template last night and fell asleep. I kanged it from BuffleHead and now we good.

**Comment by XyzKangUI** [comment]
> There is an addon "Bufflehead" that allegedly fixes the taint thats causing the combat cancel issue.

Unfortunately Bufflehead creates its own buttons/bufframe and hides blizz one. So he makes use of the secure template to be able to right click off his own created auras :/

**Comment by Evolvee** [comment]
FeelsBadMan. I rly like this addon a lot :( very simple and fixes a lot of my own "issues". If it supported debuffs too, it would be supreme.

Actually, for debuffs, you wouldnt even need to be able to right click them off as you cant do that anyways. Maybe the way is to either:

1) "rework" this addon to support debuffs only and then create either standalone addon for buffs-only similar to bufflehead but waaaaay more simple and lightweight similar to SAF

or

2) just make cancaleaura macros for things you would theorerically want to cancel (for me i can only imagine 3 buffs)

**Comment by XyzKangUI** [comment]
Actually I got a working version now where you can right click off buffs in combat. About debuffs; i need to find a way then how to "Shift+rightclick" them away lol..

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/189117044-6475b4cc-321d-4709-84b6-db48c9b95b3a.png)

Happened just now with the updated SAF version. No idea how to reproduce, I just ran on mount through AV and it occured. I didnt try to add spells to be hidden while in combat.

**Comment by XyzKangUI** [comment]
> ![image](https://user-images.githubusercontent.com/1942409/189117044-6475b4cc-321d-4709-84b6-db48c9b95b3a.png)
> 
> Happened just now with the updated SAF version. No idea how to reproduce, I just ran on mount through AV and it occured. I didnt try to add spells to be hidden while in combat.
> 
> Also, when this happens, my ToT frame on TargetFrame is hidden until reload.

The error is quite jibberish. I don't know what the issue is, but I think I'll ditch the shift right click function and add an input box. Just ran one AV myself without any errors.

**Comment by Evolvee** [comment]
Hmmm. Could be some other addon interfering with it, i will check it more today.
